/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as HomeImport } from './pages/_home'

// Create Virtual Routes

const HomeIndexLazyImport = createFileRoute('/_home/')()
const HomeAboutLazyImport = createFileRoute('/_home/about')()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  path: '/',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./pages/_home/index.lazy').then((d) => d.Route))

const HomeAboutLazyRoute = HomeAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./pages/_home/about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_home/about': {
      preLoaderRoute: typeof HomeAboutLazyImport
      parentRoute: typeof HomeImport
    }
    '/_home/': {
      preLoaderRoute: typeof HomeIndexLazyImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  HomeRoute.addChildren([HomeAboutLazyRoute, HomeIndexLazyRoute]),
])

/* prettier-ignore-end */
